# Exercises: Numpy, Scipy, Pandas
## Numpy

### 1/ Write a NumPy program to generate all floats between 0 and 10 with a step of 0.5

The program shold return an array with 0, 0.5, 1, 1.5...10

In [ ]:
import numpy as np
numpy_array=np.arange(0,10.5,0.5)
numpy_array

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

### 2/ Write a NumPy program to generate ten random numbers from the normal distribution

In [ ]:
import numpy as np
x=np.random.normal(size=10)
x

array([ 0.14221326,  0.18818319, -1.09304089,  0.62933952,  0.41200862,
        0.09578059, -0.2930803 ,  1.19916993,  1.20976136,  1.83544705])

### 3/ Write a numpy program which generate 5000 instances of a bi-variate normal distribution with means 0/0, and the covariance matrix of your choice.

In [ ]:
import numpy as np
means=[0,0]
covariance_matrix=[[1,0], [0,100]]
x=np.random.multivariate_normal(means, covariance_matrix, 5000)
x

array([[ 2.01199656, -9.96497969],
       [ 0.12966687,  4.59087298],
       [ 1.77238578, -8.37213547],
       ...,
       [-0.28593453,  3.71566369],
       [-0.06828502, -3.34149138],
       [-0.36907056, -9.65725361]])

## Scipy

### 1/ Consider the function:

f(x) = x**3-2

Using Matplotlib plot the function and using Scipy finds its root

### 2/ Calibrating a function:

You are given the below default probabilities for maturities up to year 4:


maturity=[0,1,2,3,4]

observed_default_probabilities=[0.0,0.30, 0.46, 0.58, 0.64]

The default probabilities can be modelled as an exponential distribution, with a cumulative function defined as:

$F(X)=1-e^{-\lambda X}$

Using the scipy least square minimization curve_fit, find the $\lambda$ to minimize the error  between the observed default probabilities and the model $F(X)$.

## Pandas

### Loads a dataframe from Google spreadsheet and build pivot tables

Loads the file: dividends_SX5E as a pandas dataframe

Display the 5 first rows of the dataframe

Create a pivot table which reports for each ticker the maximum price.

### Google credentials

In [ ]:
from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()

gc = gspread.authorize(creds)

### Load Excel file

In [ ]:
worksheet=gc.open('dividends_SX5E').sheet1
worksheet

<Worksheet 'Sheet1' id:0>

### Convert it to a dataframe

In [ ]:
import pandas as pd
all_values=worksheet.get_all_values()
df=pd.DataFrame.from_records(all_values[1:len(all_values)])
df.columns=all_values[0]
df

Ticker        Date Last Price Open Interest SMAVG (15)  \
0      DEDZ1 Index  2020-12-31                   247944     255564   
1      DEDZ1 Index  2020-12-30       84.8        247944     257182   
2      DEDZ1 Index  2020-12-29       84.4        247873     258601   
3      DEDZ1 Index  2020-12-28       84.7        247373     260081   
4      DEDZ1 Index  2020-12-24                   249980     261795   
...            ...         ...        ...           ...        ...   
14184   SX5E Index  2014-12-15     2982.9                            
14185   SX5E Index  2014-12-12    3067.32                            
14186   SX5E Index  2014-12-11    3159.11                            
14187   SX5E Index  2014-12-10    3150.95                            
14188   SX5E Index  2014-12-09    3162.77                            

      Future Maturity Time to maturity  
0          2021-12-31     0.9993155373  
1          2021-12-31      1.002053388  
2          2021-12-31      1.004791239  
3          2021-12-31       1.00752909  
4          2021-12-31      1.018480493  
...               ...              ...  
14184      2014-12-15                0  
14185      2014-12-12                0  
14186      2014-12-11                0  
14187      2014-12-10                0  
14188      2014-12-09                0  

[14189 rows x 7 columns]

### Display first 5 rows

In [ ]:
df.head(5)

Ticker        Date Last Price Open Interest SMAVG (15)  \
0  DEDZ1 Index  2020-12-31                   247944     255564   
1  DEDZ1 Index  2020-12-30       84.8        247944     257182   
2  DEDZ1 Index  2020-12-29       84.4        247873     258601   
3  DEDZ1 Index  2020-12-28       84.7        247373     260081   
4  DEDZ1 Index  2020-12-24                   249980     261795   

  Future Maturity Time to maturity  
0      2021-12-31     0.9993155373  
1      2021-12-31      1.002053388  
2      2021-12-31      1.004791239  
3      2021-12-31       1.00752909  
4      2021-12-31      1.018480493

### Create a pivot table with the max price for each ticker

In [ ]:
pd_max_price=pd.pivot_table(data=df, index=["Ticker"], values=["Last Price"], aggfunc=np.max)
pd_max_price

Last Price
Ticker                 
DEDZ1 Index        99.8
DEDZ16 Index      119.3
DEDZ17 Index      117.7
DEDZ18 Index       99.9
DEDZ19 Index       99.9
DEDZ2 Index        99.9
DEDZ20 Index       99.9
DEDZ3 Index        99.9
DEDZ4 Index        99.9
DEDZ5 Index        99.9
SX5E Index      3865.18